rm -rf system/system/data-app/com.dianping.v1 >>/dev/null 2>&1
rm -rf system/system/data-app/com.tencent.news_25 >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop_4 >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox_9 >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao_24 >>/dev/null 2>&1
rm -rf system/system/data-app/com.zhihu.android >>/dev/null 2>&1
rm -rf system/system/data-app/ctrip.android.view >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone_23 >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo_16 >>/dev/null 2>&1
rm -rf system/system/data-app/com.suning.mobile.ebuy >>/dev/null 2>&1
rm -rf system/system/data-app/com.tmall.wireless >>/dev/null 2>&1
rm -rf system/system/data-app/com.wuba >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.xiaomi.youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.haokan >>/dev/null 2>&1
rm -rf system/system/data-app/com.UCMobile >>/dev/null 2>&1
rm -rf system/system/data-app/com.ximalaya.ting.android >>/dev/null 2>&1
rm -rf system/system/data-app/com.ss.android.ugc.aweme >>/dev/null 2>&1
rm -rf system/system/data-app/Huanji >>/dev/null 2>&1
rm -rf system/system/data-app/tv.danmaku.bili_26 >>/dev/null 2>&1
rm -rf system/system/data-app/wps-lite >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.Qunar_18 >>/dev/null 2>&1
rm -rf system/system/vendor/data-app/SmartHome >>/dev/null 2>&1
rm -rf system/system/data-app/Health >>/dev/null 2>&1
rm -rf system/system/data-app/XMRemoteController >>/dev/null 2>&1
rm -rf system/system/data-app/com.xunmeng.pinduoduo >>/dev/null 2>&1
rm -rf system/system/app/AnalyticsCore >>/dev/null 2>&1
rm -rf system/system/app/GameCenter >>/dev/null 2>&1
rm -rf system/system/app/klobugreport >>/dev/null 2>&1
rm -rf system/system/app/mab >>/dev/null 2>&1
rm -rf system/system/data-app/com.dianping.v1 >>/dev/null 2>&1
rm -rf system/system/app/MSA-CN-NO_INSTALL_PACKAGE >>/dev/null 2>&1
rm -rf system/system/app/MSA >>/dev/null 2>&1
rm -rf system/system/app/Userguide >>/dev/null 2>&1
rm -rf system/system/app/XMPass >>/dev/null 2>&1
rm -rf system/system/data-app/BaiduIME >>/dev/null 2>&1
rm -rf system/system/data-app/MiFinance >>/dev/null 2>&1
rm -rf system/system/data-app/MiLiveAssistant >>/dev/null 2>&1
rm -rf system/system/data-app/MiMobileNoti >>/dev/null 2>&1
rm -rf system/system/data-app/MiShop >>/dev/null 2>&1
rm -rf system/system/data-app/MiTalk >>/dev/null 2>&1
rm -rf system/system/data-app/O2O >>/dev/null 2>&1
rm -rf system/system/data-app/WaliLive >>/dev/null 2>&1
rm -rf system/system/data-app/Xiangkan >>/dev/null 2>&1
rm -rf system/system/priv-app/MiDrop >>/dev/null 2>&1
rm -rf system/system/priv-app/MiGameCenterSDKService >>/dev/null 2>&1
rm -rf system/system/data-app/BaiduIME >>/dev/null 2>&1
rm -rf system/system/data-app/cn.wps.moffice_eng >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao >>/dev/null 2>&1
rm -rf system/system/data-app/com.zhihu.android >>/dev/null 2>&1
rm -rf system/system/data-app/ctrip.android.view >>/dev/null 2>&1
rm -rf system/system/data-app/GameCenter >>/dev/null 2>&1
rm -rf system/system/data-app/MiFinance >>/dev/null 2>&1
rm -rf system/system/data-app/MiLiveAssistant >>/dev/null 2>&1
rm -rf system/system/data-app/MiShop >>/dev/null 2>&1
rm -rf system/system/data-app/MiTalk >>/dev/null 2>&1
rm -rf system/system/data-app/Userguide >>/dev/null 2>&1
rm -rf system/system/data-app/O2O >>/dev/null 2>&1
rm -rf system/system/data-app/SmartHome >>/dev/null 2>&1
rm -rf system/system/data-app/XMPass >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone >>/dev/null 2>&1
rm -rf system/system/data-app/com.netease.newsreader.activity >>/dev/null 2>&1
rm -rf system/system/data-app/com.Qunar >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo >>/dev/null 2>&1
rm -rf system/system/data-app/com.suning.mobile.ebuy >>/dev/null 2>&1
rm -rf system/system/data-app/com.tmall.wireless >>/dev/null 2>&1
rm -rf system/system/data-app/com.wuba >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.xiaomi.youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.haokan >>/dev/null 2>&1
rm -rf system/system/data-app/com.UCMobile >>/dev/null 2>&1
rm -rf system/system/data-app/com.ximalaya.ting.android >>/dev/null 2>&1
rm -rf system/system/data-app/com.ss.android.ugc.aweme >>/dev/null 2>&1
rm -rf system/system/data-app/Huanji >>/dev/null 2>&1
rm -rf system/system/data-app/com.dianping.v1 >>/dev/null 2>&1
rm -rf system/system/data-app/com.tencent.news_25 >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop_4 >>/dev/null 2>&1
rm -rf system/system/data-app/com.dianping.v1_7 >>/dev/null 2>&1
rm -rf system/system/data-app/com.dragon.read_104 >>/dev/null 2>&1
rm -rf system/system/data-app/com.ss.android.article.news_76 >>/dev/null 2>&1
rm -rf system/system/data-app/com.wuba_8 >>/dev/null 2>&1
rm -rf system/system/data-app/com.smile.gifmaker_13 >>/dev/null 2>&1
rm -rf system/system/data-app/com.zhihu.android >>/dev/null 2>&1
rm -rf system/system/data-app/com.zhihu.android_28 >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox_9 >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao_24 >>/dev/null 2>&1
rm -rf system/system/data-app/ctrip.android.view >>/dev/null 2>&1
rm -rf system/system/data-app/GameCenter >>/dev/null 2>&1
rm -rf system/system/data-app/MiFinance >>/dev/null 2>&1
rm -rf system/system/data-app/MiLiveAssistant >>/dev/null 2>&1
rm -rf system/system/data-app/MiShop >>/dev/null 2>&1
rm -rf system/system/data-app/MiTalk >>/dev/null 2>&1
rm -rf system/system/data-app/Userguide >>/dev/null 2>&1
rm -rf system/system/data-app/O2O >>/dev/null 2>&1
rm -rf system/system/data-app/SmartHome >>/dev/null 2>&1
rm -rf system/system/data-app/XMPass >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone_23 >>/dev/null 2>&1
rm -rf system/system/data-app/com.netease.newsreader.activity >>/dev/null 2>&1
rm -rf system/system/data-app/com.Qunar >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo_16 >>/dev/null 2>&1
rm -rf system/system/data-app/com.suning.mobile.ebuy >>/dev/null 2>&1
rm -rf system/system/data-app/com.tmall.wireless >>/dev/null 2>&1
rm -rf system/system/data-app/com.wuba >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.xiaomi.youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.haokan >>/dev/null 2>&1
rm -rf system/system/data-app/com.UCMobile >>/dev/null 2>&1
rm -rf system/system/data-app/com.ximalaya.ting.android >>/dev/null 2>&1
rm -rf system/system/data-app/com.ss.android.ugc.aweme >>/dev/null 2>&1
rm -rf system/system/data-app/Huanji >>/dev/null 2>&1
rm -rf system/system/data-app/tv.danmaku.bili_26 >>/dev/null 2>&1
rm -rf system/system/data-app/wps-lite >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.Qunar_18 >>/dev/null 2>&1
rm -rf system/system/vendor/data-app/SmartHome >>/dev/null 2>&1
rm -rf system/system/data-app/XMRemoteController >>/dev/null 2>&1
rm -rf system/system/data-app/com.xunmeng.pinduoduo >>/dev/null 2>&1
rm -rf system/system/data-app/com.xunmeng.pinduoduo_19 >>/dev/null 2>&1
rm -rf system/system/app/AnalyticsCore >>/dev/null 2>&1
rm -rf system/system/app/GameCenter >>/dev/null 2>&1
rm -rf system/system/app/klobugreport >>/dev/null 2>&1
rm -rf system/system/app/mab >>/dev/null 2>&1
rm -rf system/system/data-app/com.dianping.v1 >>/dev/null 2>&1
rm -rf system/system/app/MSA-CN-NO_INSTALL_PACKAGE >>/dev/null 2>&1
rm -rf system/system/app/MSA >>/dev/null 2>&1
rm -rf system/system/app/Userguide >>/dev/null 2>&1
rm -rf system/system/app/XMPass >>/dev/null 2>&1
rm -rf system/system/data-app/BaiduIME >>/dev/null 2>&1
rm -rf system/system/data-app/MiFinance >>/dev/null 2>&1
rm -rf system/system/data-app/MiLiveAssistant >>/dev/null 2>&1
rm -rf system/system/data-app/MiMobileNoti >>/dev/null 2>&1
rm -rf system/system/data-app/MiShop >>/dev/null 2>&1
rm -rf system/system/data-app/MiTalk >>/dev/null 2>&1
rm -rf system/system/data-app/O2O >>/dev/null 2>&1
rm -rf system/system/data-app/WaliLive >>/dev/null 2>&1
rm -rf system/system/data-app/Xiangkan >>/dev/null 2>&1
rm -rf system/system/priv-app/MiDrop >>/dev/null 2>&1
rm -rf system/system/priv-app/MiGameCenterSDKService >>/dev/null 2>&1
rm -rf system/system/data-app/BaiduIME >>/dev/null 2>&1
rm -rf system/system/data-app/cn.wps.moffice_eng >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.searchbox >>/dev/null 2>&1
rm -rf system/system/data-app/com.taobao.taobao >>/dev/null 2>&1
rm -rf system/system/data-app/com.zhihu.android >>/dev/null 2>&1
rm -rf system/system/data-app/ctrip.android.view >>/dev/null 2>&1
rm -rf system/system/data-app/GameCenter >>/dev/null 2>&1
rm -rf system/system/data-app/MiFinance >>/dev/null 2>&1
rm -rf system/system/data-app/MiLiveAssistant >>/dev/null 2>&1
rm -rf system/system/data-app/MiShop >>/dev/null 2>&1
rm -rf system/system/data-app/MiTalk >>/dev/null 2>&1
rm -rf system/system/data-app/Userguide >>/dev/null 2>&1
rm -rf system/system/data-app/O2O >>/dev/null 2>&1
rm -rf system/system/data-app/SmartHome >>/dev/null 2>&1
rm -rf system/system/data-app/XMPass >>/dev/null 2>&1
rm -rf system/system/data-app/com.achievo.vipshop >>/dev/null 2>&1
rm -rf system/system/data-app/com.eg.android.AlipayGphone >>/dev/null 2>&1
rm -rf system/system/data-app/com.netease.newsreader.activity >>/dev/null 2>&1
rm -rf system/system/data-app/com.Qunar >>/dev/null 2>&1
rm -rf system/system/data-app/com.sina.weibo >>/dev/null 2>&1
rm -rf system/system/data-app/com.suning.mobile.ebuy >>/dev/null 2>&1
rm -rf system/system/data-app/com.tmall.wireless >>/dev/null 2>&1
rm -rf system/system/data-app/com.wuba >>/dev/null 2>&1
rm -rf system/system/data-app/Youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.xiaomi.youpin >>/dev/null 2>&1
rm -rf system/system/data-app/com.baidu.haokan >>/dev/null 2>&1
rm -rf system/system/data-app/com.UCMobile >>/dev/null 2>&1
rm -rf system/system/data-app/com.ximalaya.ting.android >>/dev/null 2>&1
rm -rf system/system/data-app/com.ss.android.ugc.aweme >>/dev/null 2>&1
rm -rf system/system/data-app/Huanji >>/dev/null 2>&1
